import { printBinaryOperationTests } from './printing_functions';

console.log(`\
import XCTest
@testable import Core

// swiftlint:disable line_length
// swiftlint:disable file_length
// swiftlint:disable function_body_length
// swiftlint:disable vertical_whitespace_closing_braces

/// Tests generated by Node.js.
/// See 'Scripts/generate_big_int_tests' for details.
class NodeTests: XCTestCase {
`);

printBinaryOperationTests('Add', (a, b) => a + b);

console.log('}');
